ALTER TABLE `cauhoi` 
CHANGE COLUMN `id_cauhoi` `id` INT(11) NOT NULL AUTO_INCREMENT ;
ALTER TABLE `dapandung` 
CHANGE COLUMN `id_dad` `id` INT(11) NOT NULL AUTO_INCREMENT ;
ALTER TABLE `dethi` 
CHANGE COLUMN `id_de` `id` INT(11) NOT NULL AUTO_INCREMENT ;
ALTER TABLE `ketqua` 
CHANGE COLUMN `id_kq` `id` INT(11) NOT NULL AUTO_INCREMENT ;
ALTER TABLE `kythi` 
CHANGE COLUMN `id_ky` `id` INT(11) NOT NULL AUTO_INCREMENT ;
ALTER TABLE `loaicauhoi` 
CHANGE COLUMN `id_loaich` `id` INT(11) NOT NULL AUTO_INCREMENT ;
ALTER TABLE `monthi` 
CHANGE COLUMN `id_mh` `id` INT(11) NOT NULL AUTO_INCREMENT ;
ALTER TABLE `mucdo` 
CHANGE COLUMN `id_mucdo` `id` INT(11) NOT NULL AUTO_INCREMENT ;
ALTER TABLE `thaoluandethi` 
DROP COLUMN `id`;
ALTER TABLE `thaoluandethi` 
CHANGE COLUMN `id_thaoluan` `id` INT(11) NOT NULL AUTO_INCREMENT ;


